<?php

namespace ContainerUmuVyrU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7JuiTMIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7JuiTMI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7JuiTMI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'todo' => ['privates', '.errored..service_locator.7JuiTMI.App\\Entity\\Todo', NULL, 'Cannot autowire service ".service_locator.7JuiTMI": it needs an instance of "App\\Entity\\Todo" but this type has been excluded in "config/services.yaml".'],
            'todoRepository' => ['privates', 'App\\Repository\\TodoRepository', 'getTodoRepositoryService', true],
        ], [
            'todo' => 'App\\Entity\\Todo',
            'todoRepository' => 'App\\Repository\\TodoRepository',
        ]);
    }
}
